main: io.github.bagas123.distancechat.Main
name: DistanceChat
version: 1.0
author: BagasMC
description: 
commands:
  localchat:
    description: Toggles local chat. 
    usage: /localchat
    permission: local.chat
    permission-message: You don't have the local.command permission.


